all:
  children:
    control_plane_nodes:
      hosts:
        control-plane:
          ansible_host: 10.0.1.1
    worker_nodes:
      hosts:
        worker-node-01:
          ansible_host: 10.0.1.2
        worker-node-02:
          ansible_host: 10.0.1.3
