resources:
  - namespaces/application.yaml
  - cert-manager/application.yaml
  - certificates/application.yaml
  - metal-lb/application.yaml
  - traefik/application.yaml
  - external-dns/application.yaml
  - longhorn/application.yaml
  - monitoring/application.yaml
  - registry/application.yaml
  - games/
  - blackbox-exporter/application.yaml
  - cnpg/application.yaml
  - jenkins/application.yaml
