---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:main
          ports:
            - name: registry-ui
              protocol: TCP
              containerPort: 80
          env:
            - name: REGISTRY_TITLE
              value: "Baremetal Registry"

            - name: REGISTRY_URL
              value: "https://registry.satriashp.cloud"

            - name: SINGLE_REGISTRY
              value: "true"

            - name: SHOW_CONTENT_DIGEST
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: registry
spec:
  type: ClusterIP
  selector:
    app: registry-ui
  ports:
    - name: registry-ui
      targetPort: 80
      port: 80
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry-ui
  namespace: traefik
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      sectionName: websecure
  hostnames:
    - registry-ui.satriashp.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: registry-ui
          port: 80
          weight: 1
          namespace: registry-ui
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry-ui-redirect
  namespace: traefik
spec:
  parentRefs:
    - name: traefik-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
      sectionName: web
  hostnames:
    - "registry-ui.satriashp.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301