# bare-metal/kubeadm/init.yaml
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration

## pre-define token so we can use it on join configuration yaml file ahead
## or just skip it and kubeadm will generete random token to join the worker-node manually.
# bootstrapTokens:
#   - groups:
#       - system:bootstrappers:kubeadm:default-node-token
#     token: abcdef.0123456789abcdef
#     ttl: 24h0m0s
#     usages:
#       - signing
#       - authentication

# localAPIEndpoint:
#   advertiseAddress: 192.168.0.60 # the real ip address if this master node, recomend to skip it, kubeadm will auto detect
#   bindPort: 6443

nodeRegistration:
  name: control-plane
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  taints: null
  # By default its pick default ipv4 on the node
  # kubeletExtraArgs:
  #   - name: node-ip
  #     value: 192.168.0.60 # the ip address of the node

timeouts:
  controlPlaneComponentHealthCheck: 4m0s
  discovery: 5m0s
  etcdAPICall: 2m0s
  kubeletHealthCheck: 4m0s
  kubernetesAPICall: 1m0s
  tlsBootstrap: 5m0s
  upgradeManifests: 5m0s

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration

clusterName: kubernetes

kubernetesVersion: 1.34.2

# single stable endpoint use by cluster to find control-plane.
# recomendation is to use DNS and use VIP with keepalived to handle IP address between control-plane nodes.
controlPlaneEndpoint: "k8s.satriashp.cloud:6443"

etcd:
  local:
    dataDir: /var/lib/etcd

networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.0.0.0/16

caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
certificatesDir: /etc/kubernetes/pki
encryptionAlgorithm: RSA-2048
imageRepository: registry.k8s.io

# Configuration for kubernetes api server
apiServer:
  certSANs:
    - "k8s.satriashp.cloud"
    - "192.168.0.200" # control-plane IP addresses

controllerManager: {}
proxy: {}
scheduler: {}
dns: {}

---
# Instead of self signing a serving certificate,
# the Kubelet will request a certificate from the 'certificates.k8s.io' API.
# This requires an approver to approve the certificate signing requests (CSR).
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
