apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-todo
  namespace: default
  labels:
    app: backend-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-todo
  template:
    metadata:
      labels:
        app: backend-todo
    spec:
      containers:
        - name: backend-todo
          image: registry.satriashp.site/backend-todo:0.1.0
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: pooler-example-rw.default
            - name: DB_USER
              value: app
            - name: DB_PASSWORD
              value: 1ineiqiKWXQx8Vg8LkvVV5ZOQYc8q7jLmDhpZSx5u65RjhcbuhUqybw1kXInWxXr
            - name: DB_NAME
              value: app
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-todo
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-todo
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: default-from-traefik
  namespace: default
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: traefik
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-todo
  namespace: traefik
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      sectionName: websecure
  hostnames:
    - backend-todo.satriashp.site
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        # - type: RequestHeaderModifier
        #   requestHeaderModifier:
        #     set:
        #     - name: X-Forwarded-Host
        #       value: "backend-todo.satriashp.site"
        #     - name: X-Forwarded-Proto
        #       value: "https"

        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: backend-todo-reverse-proxy
      backendRefs:
        - group: ""
          kind: Service
          name: backend-todo
          port: 8080
          weight: 1
          namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-todo-redirect
  namespace: traefik
spec:
  parentRefs:
    - name: traefik-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
      sectionName: web
  hostnames:
    - "backend-todo.satriashp.site"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: backend-todo-reverse-proxy
  namespace: traefik
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "http"
      X-Forwarded-Host: "backend-todo.satriashp.site"
